//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTrainingList
    {
        public int Id { get; set; }
        public string TrainingName { get; set; }
        public Datetime StartDate{ get; set; }
        public Datetime EndDate{ get; set; }
    }
}
